name:                tetris
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/artur3303/tetris#readme
license:             BSD3
author:              AKarpov
maintainer:          artik100313@gmail.com
copyright:           2018 AKarpov
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  tetris:
    source-dirs:      src
    main:             Main.hs
