name:                haskell-ping-pong
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/artur3303/haskell-ping-pong#readme
license:             BSD3
author:              AKarpov, RNovikov, RAkhmadiev, MAndreichev
#maintainer:          
copyright:           2018 MD
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - gloss

executables:
  haskell-ping-pong:
    source-dirs:      src
    main:             Main.hs
